version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommercedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: E-Commerce-Backend/Dockerfile
    container_name: ecommerce-app
    depends_on:
      - mysql
    ports:
      - "8009:8009"

volumes:
  mysql_data:
